#import "BBAction.h"

@interface BBBulletin : NSObject

// @property (nonatomic, retain) BBAccessoryIcon *accessoryIconMask;
@property (nonatomic, copy) BBAction *acknowledgeAction;
@property (nonatomic, copy) NSMutableDictionary *actions;
@property (nonatomic) int addressBookRecordID;
@property (nonatomic, readonly) NSSet *alertSuppressionAppIDs;
@property (nonatomic, copy) NSSet *alertSuppressionAppIDs_deprecated;
@property (nonatomic, copy) NSSet *alertSuppressionContexts;
@property (nonatomic, readonly) BOOL allowsAddingToLockScreenWhenUnlocked;
@property (nonatomic, readonly) BOOL allowsAutomaticRemovalFromLockScreen;
@property (nonatomic, copy) BBAction *alternateAction;
@property (nonatomic, readonly) NSString *alternateActionLabel;
// @property (nonatomic, retain) BBAttachments *attachments;
@property (nonatomic, readonly) NSString *bannerAccessoryRemoteServiceBundleIdentifier;
@property (nonatomic, readonly) NSString *bannerAccessoryRemoteViewControllerClassName;
@property (nonatomic, copy) NSString *bulletinID;
@property (nonatomic, copy) NSString *bulletinVersionID;
@property (nonatomic, copy) NSArray *buttons;
@property (nonatomic, readonly) BOOL canBeSilencedByMenuButtonPress;
@property (nonatomic) BOOL clearable;
@property (nonatomic, readonly) BOOL coalescesWhenLocked;
// @property (nonatomic, retain) BBContent *content;
@property (nonatomic, retain) NSDictionary *context;
@property (nonatomic) unsigned int counter;
@property (nonatomic, retain) NSDate *date;
@property (nonatomic) int dateFormatStyle;
@property (nonatomic) BOOL dateIsAllDay;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, copy) BBAction *defaultAction;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) NSString *dismissalID;
@property (nonatomic, retain) NSDate *endDate;
@property (nonatomic, retain) NSDate *expirationDate;
@property (nonatomic) unsigned int expirationEvents;
@property (nonatomic, copy) BBAction *expireAction;
@property (nonatomic) BOOL expiresOnPublisherDeath;
@property (nonatomic, readonly) NSString *fullAlternateActionLabel;
@property (nonatomic, readonly) NSString *fullUnlockActionLabel;
@property (nonatomic) BOOL hasEventDate;
@property (readonly) unsigned int hash;
@property (nonatomic, readonly) int iPodOutAlertType;
@property (nonatomic, readonly) BOOL ignoresQuietMode;
@property (nonatomic, readonly) BOOL inertWhenLocked;
@property (nonatomic, retain) NSDate *lastInterruptDate;
@property (nonatomic, retain) NSMutableArray *lifeAssertions;
@property (getter=isLoading, nonatomic) BOOL loading;
@property (nonatomic, copy) NSString *message;
@property (nonatomic, readonly) unsigned int messageNumberOfLines;
@property (nonatomic, readonly) NSString *missedBannerDescriptionFormat;
// @property (nonatomic, retain) BBContent *modalAlertContent;
@property (nonatomic, retain) NSMutableSet *observers;
@property (nonatomic, readonly) BOOL orderSectionUsingRecencyDate;
@property (nonatomic, copy) NSString *parentSectionID;
@property (nonatomic, readonly) BOOL playsSoundForModify;
@property (nonatomic, readonly) BOOL preservesUnlockActionCase;
@property (nonatomic, readonly) BOOL preventLock;
@property (nonatomic, readonly) int primaryAttachmentType;
@property (nonatomic, retain) NSDate *publicationDate;
@property (nonatomic, copy) NSString *publisherBulletinID;
@property (nonatomic, copy) BBAction *raiseAction;
@property (nonatomic, readonly) unsigned int realertCount;
@property (nonatomic) unsigned int realertCount_deprecated;
@property (nonatomic, retain) NSDate *recencyDate;
@property (nonatomic, copy) NSString *recordID;
@property (nonatomic, readonly) NSString *secondaryContentRemoteServiceBundleIdentifier;
@property (nonatomic, readonly) NSString *secondaryContentRemoteViewControllerClassName;
@property (nonatomic, copy) NSString *section;
@property (nonatomic, readonly) NSString *sectionDisplayName;
@property (nonatomic, readonly) BOOL sectionDisplaysCriticalBulletins;
@property (nonatomic, copy) NSString *sectionID;
// @property (nonatomic, readonly) BBSectionIcon *sectionIcon;
@property (nonatomic) int sectionSubtype;
@property (nonatomic, readonly) BOOL showsContactPhoto;
@property (nonatomic, readonly) BOOL showsDateInFloatingLockScreenAlert;
@property (nonatomic) BOOL showsMessagePreview;
@property (nonatomic, readonly) BOOL showsSubtitle;
@property (nonatomic, readonly) BOOL showsUnreadIndicatorForNoticesFeed;
@property (nonatomic, copy) BBAction *snoozeAction;
// @property (nonatomic, retain) BBSound *sound;
// @property (nonatomic, retain) BBContent *starkBannerContent;
@property (nonatomic, copy) NSSet *subsectionIDs;
@property (nonatomic, copy) NSString *subtitle;
@property (nonatomic, readonly) unsigned int subtypePriority;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSMutableDictionary *supplementaryActionsByLayout;
@property (nonatomic, readonly) BOOL suppressesAlertsWhenAppIsActive;
@property (nonatomic, readonly) BOOL suppressesMessageForPrivacy;
@property (nonatomic, readonly) BOOL suppressesTitle;
@property (nonatomic, retain) NSTimeZone *timeZone;
// @property (nonatomic, readonly) BBColor *tintColor;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, readonly) NSString *topic;
@property (nonatomic, copy) NSString *universalSectionID;
@property (nonatomic, readonly) NSString *unlockActionLabel;
@property (nonatomic, copy) NSString *unlockActionLabelOverride;
@property (nonatomic) BOOL usesExternalSync;
@property (nonatomic, readonly) BOOL usesVariableLayout;
@property (nonatomic, readonly) BOOL visuallyIndicatesWhenDateIsInFuture;
@property (nonatomic) BOOL wantsFullscreenPresentation;

@end